name: build
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: "gcr.io/radicle-upstream/radicle-upstream-ci:14"
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
          key: build-${{ runner.os }}-yarn-v3-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-${{ runner.os }}-yarn-v3-
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/cargo
            ~/cache/proxy-target
          key: build-${{ runner.os }}-rust-v1-${{ hashFiles('Cargo.lock') }}
      - run: ci/run.sh
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: linux-test-logs
          path: |
            cypress/screenshots/**/*.png
            cypress/workspace/test-tmp/*/node-*/*.log
            cypress/workspace/test-tmp/*/combined-node.log
      - uses: actions/upload-artifact@v2
        with:
          name: linux-dist
          path: |
            dist/*.AppImage

  # Dummy build
  build-macos:
    runs-on: ubuntu-latest
    container:
      image: "gcr.io/radicle-upstream/radicle-upstream-ci:14"
    steps:
      - uses: actions/checkout@master
      - run: |
          mkdir dist
          echo jo > dist/foo.dmg
      - uses: actions/upload-artifact@v2
        with:
          name: macos-dist
          path: |
            dist/*.dmg

  publish-artifacts:
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/thomas/') }}
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux-dist
          path: dist
      - uses: actions/download-artifact@v2
        with:
          name: macos-dist
          path: dist
      - run: ls dist
      - name: publish artifacts by commit
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: dist
          destination: radicle-upstream-build-artifacts/v1/by-commit/${{ github.sha }}
          credentials: ${{ secrets.GCP_SECRET_KEY }}
          parent: false
      - name: publish master artifacts
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: dist
          destination: radicle-upstream-build-artifacts/v1/master/
          credentials: ${{ secrets.GCP_SECRET_KEY }}
          parent: false
